---
# Copyright 2016 Internet Solutions (Pty) Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# (c) 2016 Donovan Francesco <donovan.francesco@is.co.za>
# (c) 2016 Paul Stevens <paul.stevens@is.co.za>
- name: Place the init script
  template:
    src: "monasca-upstart-init.j2"
    dest: "/etc/init/{{ program_name }}.conf"
    mode: "0644"
    owner: "root"
    group: "root"
  register: upstart_init
  notify:
    - Restart monasca api services
    - Restart monasca events api services
    - Restart monasca log api services
    - Restart monasca ceilometer services
    - Restart monasca common services
    - Restart monasca thresh services
    - Restart monasca transform services
    - Restart monasca notification services
    - Restart monasca analytics services
    - Restart monasca persister services
    - Restart Apache

- name: Reload init scripts
  shell: |
    initctl reload-configuration
  when: upstart_init | changed
  notify:
    - Restart monasca api services
    - Restart monasca events api services
    - Restart monasca log api services
    - Restart monasca ceilometer services
    - Restart monasca common services
    - Restart monasca transform services
    - Restart monasca notification services
    - Restart monasca analytics services
    - Restart monasca persister services
    - Restart Apache
