---
# Copyright 2016 Internet Solutions (Pty) Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# (c) 2016 Donovan Francesco <donovan.francesco@is.co.za>
# (c) 2016 Paul Stevens <paul.stevens@is.co.za>

# Create a service
- name: Ensure monasca service
  keystone:
    command: "ensure_service"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    service_name: "{{ monasca_service_name }}"
    service_type: "{{ monasca_service_type }}"
    description: "{{ monasca_service_description }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 2
  no_log: True

# Create an admin user
- name: Ensure monasca user
  keystone:
    command: "ensure_user"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    user_name: "{{ monasca_service_user_name }}"
    tenant_name: "{{ monasca_service_project_name }}"
    password: "{{ monasca_service_password }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_user
  when: not monasca_service_in_ldap | bool
  until: add_user|success
  retries: 5
  delay: 10
  no_log: True

# Add a role to the user
- name: Ensure monasca user to admin role
  keystone:
    command: "ensure_user_role"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    user_name: "{{ monasca_service_user_name }}"
    tenant_name: "{{ monasca_service_project_name }}"
    role_name: "{{ monasca_role_name }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_user_role
  when: not monasca_service_in_ldap | bool
  until: add_user_role|success
  retries: 5
  delay: 10
  no_log: True

# Create monasca roles
- name: Ensure monasca user, agent and read only roles
  keystone:
    command: "ensure_role"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    role_name: "{{ item }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_roles
  when: not monasca_service_in_ldap | bool
  until: add_roles|success
  retries: 5
  delay: 10
  no_log: True
  with_flattened:
    - "{{ monasca_user_roles }}"
    - "{{ monasca_agent_roles }}"
    - "{{ monasca_read_only_user_roles }}"

# Create an monasca-agent user
- name: Ensure monasca-agent user
  keystone:
    command: "ensure_user"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    user_name: "{{ monasca_agent_user_name }}"
    tenant_name: "{{ monasca_agent_project_name }}"
    password: "{{ monasca_agent_password }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_user
  when: not monasca_service_in_ldap | bool
  until: add_user|success
  retries: 5
  delay: 10
  no_log: True

# Add a role to the user
- name: Ensure monasca-agent user to monasca-agent roles
  keystone:
    command: "ensure_user_role"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    user_name: "{{ monasca_agent_user_name }}"
    tenant_name: "{{ monasca_agent_project_name }}"
    role_name: "{{ item }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_user_role
  when: not monasca_service_in_ldap | bool
  until: add_user_role|success
  retries: 5
  delay: 10
  no_log: True
  with_items: "{{ monasca_agent_roles }}"

# Add a role to the user
- name: Ensure admin user to monasca-user roles
  keystone:
    command: "ensure_user_role"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    user_name: "{{ keystone_admin_user_name }}"
    tenant_name: "{{ keystone_admin_tenant_name }}"
    role_name: "{{ item }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_user_role
  when: not monasca_service_in_ldap | bool
  until: add_user_role|success
  retries: 5
  delay: 10
  no_log: True
  with_items: "{{ monasca_user_roles }}"

# Create an endpoint
- name: Ensure monasca endpoint
  keystone:
    command: "ensure_endpoint"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    region_name: "{{ monasca_service_region }}"
    service_name: "{{ monasca_service_name }}"
    service_type: "{{ monasca_service_type }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
    endpoint_list:
      - url: "{{ monasca_service_publicurl }}"
        interface: "public"
      - url: "{{ monasca_service_internalurl }}"
        interface: "internal"
      - url: "{{ monasca_service_adminurl }}"
        interface: "admin"
  register: add_endpoint
  until: add_endpoint|success
  retries: 5
  delay: 10
  no_log: True
