---
# Copyright 2016 Internet Solutions (Pty) Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# (c) 2016 Donovan Francesco <donovan.francesco@is.co.za>
# (c) 2016 Paul Stevens <paul.stevens@is.co.za>
- name: Update Apt sources
  apt:
    update_cache: yes
  register: apt_update
  until: apt_update | success
  retries: 5
  delay: 2

- name: Install Apt dependencies
  apt:
    pkg: "{{ item }}"
    state: "latest"
  register: install_deps
  until: install_deps | success
  retries: 5
  delay: 2
  with_items: "{{ monasca_distro_packages }}"

- include: pre-zookeeper-install.yml
  when:
    - enable_zookeeper is defined
    - inventory_hostname in groups['monasca_zookeeper']

- include: pre-kafka-install.yml
  when:
    - enable_kafka is defined
    - inventory_hostname in groups['monasca_kafka']

- include: pre-storm-install.yml
  when:
    - enable_storm is defined
    - inventory_hostname in groups['monasca_storm']

- include: pre-influxdb-install.yml
  when:
    - enable_influxdb is defined
    - inventory_hostname in groups['monasca_influxdb']

- include: pre-grafana-install.yml
  when:
    - enable_grafana is defined
    - inventory_hostname in groups['monasca_grafana']
